json.name 			@user.name
json.username 		@user.username
json.email 			@user.email
json.birthday 		@user.birthday
json.gender 		@user.gender
json.address 		@user.address
json.phone 			@user.phone	
json.avatar 		@user.avatar.url
json.cover 			@user.cover
json.money 			@user.money
json.user_exp 		@user.user_exp
