hmac_secret: 'fQ+KY11&l624Bu5'
timeAddHeart: 30
# magebanks
magebankWS: 'http://203.128.244.163:8015/Service.asmx?wsdl'
magebankMerchantid: 'TA123'
magebankIssuerID: '18800110'
magebankSend_key: 'reesatersuusrtiy12312kty'
magebankReceived_key: 'k43423553535gsgrthkladgt'
# SMS
partnerid: '10184'
partnerpass: 'b1d12048be86cf96b767b8b739b2679e'
# BaseURL
base_url: 'http://api.dev.livestar.vn/'