hmac_secret: 'fQ+KY11&l624Bu5'
timeAddHeart: 30
# Charging
chargingUsername: 'Livestar'
chargingPassword: 'bgrkhsngw'
chargingMpin: 'hshijmhif'
chargingPartnerId: 'Livestar'
chargingPartnerCode: '01085'
chargingWebservice: 'http://charging-service.megapay.net.vn/CardChargingGW_V2.0/services/Services?wsdl'
# magebanks
magebankWS: 'http://bank.megapay.net.vn:10001/service.asmx?wsdl'
magebankMerchantid: 'Livestar'
magebankIssuerID: '88000095'
magebankSend_key: 'X9557IMmIMRKOPVs6twAqQOi'
magebankReceived_key: 'Qqy0GKhecgDuStT6h6zyKkzU'
# SMS
partnerid: '10184'
partnerpass: 'b1d12048be86cf96b767b8b739b2679e'
# BaseURL
base_url: 'http://api.dev.livestar.vn/'