 # Cấu hình dành cho Production
 # Không được tự ý thay đổi thông số này
redis_host: "localhost"
redis_port: 6379
livestar_path: "http://livestar.vn"
m_livestar_path: "http://m.livestar.vn"
base_url: 'http://api.livestar.vn/'
